### ISSUE TITLE
LPに使う画像でUser Groupに関するものを集めたい

### ISSUE THREAD

**Issue by motuo1201** [motuo1201/IBM-User-Conf-LP#5]

**Comment by kolinz** [comment]
BMXUGが関係できるものであれば、ぶるみちゃん画像がありますよ。https://www.facebook.com/groups/bmxug/permalink/1513298498722256/

**Comment by motuo1201** [comment]
@kolinz ありがとうございます！HPの画像を一部、差し替えてみました。
